# Site settings
title: Gavin's Personal Website
description: A website showcasing my personal work and interests
baseurl: "" # the subpath of your site, e.g. /blog
url: "gavinhardin.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gavin Hardin
user_description: I'm a graduating student in computer science from NCSU. In my coursework, I've learned how to design, build, test, and maintain software systems, and would love to prove it to you. My interests range from machine learning to database management, and I believe I can apply myself to wherever I'm needed. I feel comfortable working in skilled groups, but have taken on the mantle of leading projects in the past and have no problem with taking on the responsibility again.
user_title: Software Developer
email: gavinchardin@gmail.com
# twitter_username: lorem_ipsum
github_username:  gavinhardin
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
